export const POSITIONS = [
  "TOP",
  "JUNGLE",
  "MIDDLE",
  "BOTTOM",
  "UTILITY",
] as const;

export type Position = (typeof POSITIONS)[number];

export function isPosition(value: unknown): value is Position {
  return POSITIONS.includes(value as Position);
}

export const LANE_LABELS: Record<Position, string> = {
  TOP: "TOP",
  JUNGLE: "JG",
  MIDDLE: "MID",
  BOTTOM: "ADC",
  UTILITY: "SUP",
};

export interface Champion {
  /** Data Dragon id (e.g. "Aatrox") — also the image filename stem */
  id: string;
  /** numeric key (e.g. "266") */
  key: string;
  name: string;
  title: string;
  tags: string[];
  positions: Position[];
  /** Q/W/E/R skill names */
  spells: string[];
  passive: string;
}

export interface Item {
  /** numeric id — also the image filename stem */
  id: string;
  name: string;
  /** short plain-text effect summary (may be empty) */
  plaintext: string;
  /** total gold cost */
  price: number;
  tags: string[];
}

export interface RuneStyle {
  /** e.g. "覇道", "栄華" */
  name: string;
  runes: string[];
}

export interface SummonerSpell {
  id: string;
  name: string;
  description: string;
  cooldown: number;
}

export interface QuizData {
  version: string;
  generatedAt: string;
  champions: Champion[];
  items: Item[];
  runeStyles: RuneStyle[];
  summonerSpells: SummonerSpell[];
}

const DDRAGON_CDN = "https://ddragon.leagueoflegends.com/cdn";

export function championImageUrl(data: QuizData, champion: Champion): string {
  return `${DDRAGON_CDN}/${data.version}/img/champion/${champion.id}.png`;
}

export function itemImageUrl(data: QuizData, item: Item): string {
  return `${DDRAGON_CDN}/${data.version}/img/item/${item.id}.png`;
}

let cache: Promise<QuizData> | undefined;

/** Load the quiz source data (generated by scripts/generate-data.ts). */
export function loadQuizData(): Promise<QuizData> {
  cache ??= fetch(`${import.meta.env.BASE_URL}data/quiz-data.json`).then(
    (res) => {
      if (!res.ok) throw new Error(`Failed to load quiz data: ${res.status}`);
      return res.json() as Promise<QuizData>;
    },
  );
  return cache;
}
