export const POSITIONS = [
  "TOP",
  "JUNGLE",
  "MIDDLE",
  "BOTTOM",
  "UTILITY",
] as const;

export type Position = (typeof POSITIONS)[number];

export function isPosition(value: unknown): value is Position {
  return POSITIONS.includes(value as Position);
}

export const LANE_LABELS: Record<Position, string> = {
  TOP: "TOP",
  JUNGLE: "JG",
  MIDDLE: "MID",
  BOTTOM: "ADC",
  UTILITY: "SUP",
};

export const SPELL_SLOTS = ["Q", "W", "E", "R"] as const;

export type SpellSlot = (typeof SPELL_SLOTS)[number];

export interface ChampionSpell {
  slot: SpellSlot;
  name: string;
  /** plain-text effect description */
  description: string;
  /** image filename under cdn img/spell/ */
  image: string;
}

export interface ChampionPassive {
  name: string;
  description: string;
  /** image filename under cdn img/passive/ */
  image: string;
}

export interface Champion {
  /** Data Dragon id (e.g. "Aatrox") — also the image filename stem */
  id: string;
  /** numeric key (e.g. "266") */
  key: string;
  name: string;
  /** English name (e.g. "Kai'Sa") for hard-mode search */
  nameEn: string;
  title: string;
  tags: string[];
  positions: Position[];
  /** Q/W/E/R skills */
  spells: ChampionSpell[];
  passive: ChampionPassive;
}

export interface Item {
  /** numeric id — also the image filename stem */
  id: string;
  name: string;
  /** English name for hard-mode search */
  nameEn: string;
  /**
   * In-game description as multi-line plain text: stat lines
   * (e.g. "魔力 30") followed by 【パッシブ名】 and effect text.
   */
  description: string;
  /** total gold cost */
  price: number;
  tags: string[];
}

export interface Rune {
  name: string;
  /** English name for hard-mode search */
  nameEn: string;
  /** icon path under cdn img/ (e.g. "perk-images/Styles/...") */
  icon: string;
  /** plain-text effect summary */
  description: string;
}

export interface RuneStyle {
  /** e.g. "覇道", "栄華" */
  name: string;
  /** icon path under cdn img/ */
  icon: string;
  runes: Rune[];
}

export interface SummonerSpell {
  id: string;
  name: string;
  /** English name for hard-mode search */
  nameEn: string;
  description: string;
  cooldown: number;
}

export interface QuizData {
  version: string;
  generatedAt: string;
  champions: Champion[];
  items: Item[];
  runeStyles: RuneStyle[];
  summonerSpells: SummonerSpell[];
}

// Images stay on the Data Dragon CDN (self-hosting them is not clearly
// permitted by Riot's policies). public/sw.js caches them on the user's
// device: once displayed — or pre-downloaded from the home screen — they
// are served from local Cache Storage.
export const DDRAGON_CDN = "https://ddragon.leagueoflegends.com/cdn";

export function championImageUrl(data: QuizData, champion: Champion): string {
  return `${DDRAGON_CDN}/${data.version}/img/champion/${champion.id}.png`;
}

export function itemImageUrl(data: QuizData, item: Item): string {
  return `${DDRAGON_CDN}/${data.version}/img/item/${item.id}.png`;
}

export function summonerSpellImageUrl(
  data: QuizData,
  spell: SummonerSpell,
): string {
  return `${DDRAGON_CDN}/${data.version}/img/spell/${spell.id}.png`;
}

export function championSpellImageUrl(
  data: QuizData,
  spell: ChampionSpell,
): string {
  return `${DDRAGON_CDN}/${data.version}/img/spell/${spell.image}`;
}

export function championPassiveImageUrl(
  data: QuizData,
  passive: ChampionPassive,
): string {
  return `${DDRAGON_CDN}/${data.version}/img/passive/${passive.image}`;
}

/** Rune / rune style icons are unversioned on the CDN. */
export function runeImageUrl(icon: string): string {
  return `${DDRAGON_CDN}/img/${icon}`;
}

let cache: Promise<QuizData> | undefined;

/** Load the quiz source data (generated by scripts/generate-data.ts). */
export function loadQuizData(): Promise<QuizData> {
  cache ??= fetch(`${import.meta.env.BASE_URL}data/quiz-data.json`).then(
    (res) => {
      if (!res.ok) throw new Error(`Failed to load quiz data: ${res.status}`);
      return res.json() as Promise<QuizData>;
    },
  );
  return cache;
}
